UPDATE products SET image = '/uploads/products/Cookie Croissant.jpg' WHERE id = 53;
UPDATE products SET image = '/uploads/products/Pain au Chocolat.jpg' WHERE id = 54;
UPDATE products SET image = '/uploads/products/Nutella New York Roll.jpg' WHERE id = 55;
UPDATE products SET image = '/uploads/products/Fruit Danish.jpg' WHERE id = 56;
UPDATE products SET image = '/uploads/products/Raspberry Cream Cheese.jpg' WHERE id = 57;
UPDATE products SET image = '/uploads/products/Chocolate Mousse.jpg' WHERE id = 58;
UPDATE products SET image = '/uploads/products/Lemon Pie Croissant.jpg' WHERE id = 59;
UPDATE products SET image = '/uploads/products/Almond Croissant.jpg' WHERE id = 60;
UPDATE products SET image = '/uploads/products/Pistachio & Raspberry.jpg' WHERE id = 61;
UPDATE products SET image = '/uploads/products/Dulce de Leche.jpg' WHERE id = 62;
UPDATE products SET image = '/uploads/products/Strawberry Croissant.jpg' WHERE id = 63;
UPDATE products SET image = '/uploads/products/Dubai Chocolate.jpg' WHERE id = 64;
UPDATE products SET image = '/uploads/products/Artisanal Croissant.jpg' WHERE id = 65;
UPDATE products SET image = '/uploads/products/Emerald Temptation.jpg' WHERE id = 66;
UPDATE products SET image = '/uploads/products/Zesty Lemon.jpg' WHERE id = 67;
UPDATE products SET image = '/uploads/products/Classic Tres Leches.jpg' WHERE id = 68;
UPDATE products SET image = '/uploads/products/Apple Essence.jpg' WHERE id = 69;
UPDATE products SET image = '/uploads/products/Berry Cloud Pavlova.jpg' WHERE id = 70;
UPDATE products SET image = '/uploads/products/Tiramisú.jpg' WHERE id = 71;
UPDATE products SET image = '/uploads/products/Creamy Dulce Temptation.jpg' WHERE id = 72;
UPDATE products SET image = '/uploads/products/Triple Chocolate.jpg' WHERE id = 73;
UPDATE products SET image = '/uploads/products/Tropical Bliss.jpg' WHERE id = 74;
UPDATE products SET image = '/uploads/products/Pear Harmony.jpg' WHERE id = 75;
UPDATE products SET image = '/uploads/products/Crème Brûlée.jpg' WHERE id = 76;
UPDATE products SET image = '/uploads/products/Blueberry Heart.jpg' WHERE id = 77;
UPDATE products SET image = '/uploads/products/Napoleon.jpg' WHERE id = 78;
UPDATE products SET image = '/uploads/products/Dark Passion.jpg' WHERE id = 79;
UPDATE products SET image = '/uploads/products/Golden Crunch.jpg' WHERE id = 80;
UPDATE products SET image = '/uploads/products/Golden Love.jpg' WHERE id = 81;
UPDATE products SET image = '/uploads/products/Caramel Banana Bliss.jpg' WHERE id = 82;
UPDATE products SET image = '/uploads/products/Fruit Tart.jpg' WHERE id = 83;
UPDATE products SET image = '/uploads/products/Mango Coco Dream.jpg' WHERE id = 84;
UPDATE products SET image = '/uploads/products/Orange Blossom Delight.jpg' WHERE id = 85;
UPDATE products SET image = '/uploads/products/Rosa Elegance.jpg' WHERE id = 86;
UPDATE products SET image = '/uploads/products/Raspberry Secret.jpg' WHERE id = 87;
UPDATE products SET image = '/uploads/products/Piña Colada Dream.jpg' WHERE id = 88;
UPDATE products SET image = '/uploads/products/Mango Tres Leches.jpg' WHERE id = 89;
UPDATE products SET image = '/uploads/products/Strawberry Bliss.jpg' WHERE id = 90;
UPDATE products SET image = '/uploads/products/Mocca Chocolate_p.jpg' WHERE id = 91;
UPDATE products SET image = '/uploads/products/carrot_p_p.jpg' WHERE id = 92;
UPDATE products SET image = '/uploads/products/BlackForest_p_p.jpg' WHERE id = 93;
UPDATE products SET image = '/uploads/products/White Chocolat_p.jpg' WHERE id = 94;
UPDATE products SET image = '/uploads/products/red_velvet_p_p.jpg' WHERE id = 95;
UPDATE products SET image = '/uploads/products/NewYork_p_p.jpg' WHERE id = 96;
UPDATE products SET image = '/uploads/products/Mango Cheesecake_p.jpg' WHERE id = 97;
UPDATE products SET image = '/uploads/products/Tiramisu_p.jpg' WHERE id = 98;
UPDATE products SET image = '/uploads/products/Dulce de Leche_p.jpg' WHERE id = 99;
UPDATE products SET image = '/uploads/products/Strawberry_p.jpg' WHERE id = 100;
UPDATE products SET image = '/uploads/products/e5822692d8d14bcb757ef663.jpg' WHERE id = 101;
UPDATE products SET image = '/uploads/products/f410e842d95da310419eda4ab7.jpg' WHERE id = 102;
UPDATE products SET image = '/uploads/products/test.jpg' WHERE id = 103;
UPDATE products SET image = '/uploads/products/f410e842d95da310419eda4ab7.jpg' WHERE id = 104;
